name: Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Docker on macOS
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install --cask docker
          open /Applications/Docker.app
          while ! docker system info > /dev/null 2>&1; do
            echo "Waiting for Docker to start..."
            sleep 1
          done

      - name: Pull Docker image
        run: docker pull --platform linux/amd64 kevkibe/memvectordb:latest

      - name: Run Docker container
        run: docker run -d --platform linux/amd64 -p 8000:8000 kevkibe/memvectordb

      - name: Install dependencies
        run: |
          pip install -r requirements.txt --no-cache-dir
          pip install pytest einops lion-pytorch

      - name: Run Tests
        run: pytest
