name: MemVectorDB Tests

on: [pull_request]


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Pull Docker image
        run: docker pull --platform linux/amd64 kevkibe/memvectordb:latest

      - name: Run Docker container
        run: docker run -d --platform linux/amd64 -p 8000:8000 kevkibe/memvectordb

      - name: Install dependencies
        run: |
          pip install -r requirements.txt --no-cache-dir
          pip install pytest einops lion-pytorch

      - name: Run Tests
        run: pytest
